In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
# transition matrix
P = [[0.2,0.6,0.2],[0.3,0,0.7],[0,0.5,0.5]]
# state space
state_space = ['r','g','d']

# with sanity check
assert np.allclose(np.sum(P, axis=1), np.ones(len(state_space)))

# predict weather
def weather(x0):
  i = state_space.index(x0)
  while True:
    yield state_space[i]
    i = np.random.choice(len(state_space),p=P[i])
  
# initialise the weather condition
x = weather(x0='r')

for index in range(10):
  print(f'On day {index}, weather {next(x)}')

On day 0, weather r
On day 1, weather g
On day 2, weather d
On day 3, weather g
On day 4, weather d
On day 5, weather d
On day 6, weather g
On day 7, weather r
On day 8, weather g
On day 9, weather d


In [12]:
# multi-step transitions
P = np.array(P)

p_x2_r = (P @ P)[2,0] # compute P^2 then pick out element at [2,0]
# alternatively, use
p_x2_r2 = np.linalg.matrix_power(P,2)[2,0]
(p_x2_r, p_x2_r2) # (0.15, 0.15)

(0.15, 0.15)

In [13]:
P

array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0. , 0.5, 0.5]])

In [14]:
(P @ P)

array([[0.22, 0.22, 0.56],
       [0.06, 0.53, 0.41],
       [0.15, 0.25, 0.6 ]])

In [15]:
# 100-step transition probabilities
# the probability in state j converges to pi_j, the stationary distribution, after very many steps
np.linalg.matrix_power(P,100)

array([[0.12820513, 0.34188034, 0.52991453],
       [0.12820513, 0.34188034, 0.52991453],
       [0.12820513, 0.34188034, 0.52991453]])

In [37]:
# state are in order [alpha,beta,gamma,delta,epsilon,w]
# set up an adjacency matrix for the graph, scale it so rows sum to 1
P = np.array([[0,1,1,0,0,0],[0,0,0,1,1,0],[1,0,0,0,0,1],
              [0,1,0,0,0,1],[1,0,0,0,0,0],[0,0,1,0,1,0]])


P = P / P.sum(axis=1)[:,np.newaxis]
P

array([[0. , 0.5, 0.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0.5, 0. ],
       [0.5, 0. , 0. , 0. , 0. , 0.5],
       [0. , 0.5, 0. , 0. , 0. , 0.5],
       [1. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.5, 0. , 0.5, 0. ]])

In [38]:
assert all(P.sum(axis=1)==1)

In [42]:
# solve  P π = π i.e. (P − I)π = 0, except for πα and πw
# bundle all the equations together in a matrix, and solve with np.linalg,lstsq
A = P - np.eye(6) # diagonal square matrix np.eye()
A[0,:] = [1,0,0,0,0,0] # except for πα
A[5,:] = [0,0,0,0,0,1] # except for πw
b = np.zeros(6)
b[5] = 1
pi = np.linalg.lstsq(A,b)[0]

# return the hitting probability
hit_prob = (P @ pi)[0]
print(pi)
print(f'Hitting probability:{hit_prob}')

[1.66262876e-16 3.33333333e-01 5.00000000e-01 6.66666667e-01
 4.02208849e-16 1.00000000e+00]
Hitting probability:0.41666666666666724


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  
